name: CI - Catppuccin GTK Mocha

on:
  push:
    branches:
      - "main"
    paths:
      - "catppuccin-gtk-theme-mocha/.SRCINFO"
      - "catppuccin-gtk-theme-mocha/PKGBUILD"
  pull_request:
    branches:
      - "main"
    paths:
      - "catppuccin-gtk-theme-mocha/.SRCINFO"
      - "catppuccin-gtk-theme-mocha/PKGBUILD"
  workflow_dispatch:
    inputs:
      version:
        description: "Upstream synced version"
        default: ""
        required: false

env:
  PACKAGE: catppuccin-gtk-theme-mocha

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: "${{ env.PACKAGE }}"
          namcap: false

  release:
    name: Release package
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set commit message
        id: commit
        run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            COMMIT_MESSAGE="chore: update AUR package"
          elif [[ -n "${{ github.event.inputs.version }}" ]]; then
            COMMIT_MESSAGE="chore: bump to ${{ github.event.inputs.version }}"
          fi

          echo "::set-output name=message::$COMMIT_MESSAGE"

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: ${{ env.PACKAGE }}
          pkgbuild: ${{ env.PACKAGE }}/PKGBUILD
          commit_username: ${{ secrets.GIT_USERNAME }}
          commit_email: ${{ secrets.GIT_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_PRIVATE_SSH_KEY }}
          commit_message: ${{ steps.commit.outputs.message }}
          allow_empty_commits: false
          force_push: true
